application:
  name: Sample Application
  version: 1.0.0
  homepage: https://example.com
  repository: https://github.com/username/project
  documentation: https://docs.example.com

api:
  base_url: https://api.example.com/v1
  endpoints:
    users: https://api.example.com/v1/users
    posts: https://api.example.com/v1/posts
    search: https://api.example.com/v1/search
  health_check: https://api.example.com/health
  status_page: https://status.example.com

cdn:
  images: https://cdn.example.com/images
  scripts: https://cdn.example.com/js
  styles: https://cdn.example.com/css
  fonts: https://fonts.googleapis.com/css2

external_services:
  analytics: https://analytics.example.com/track
  monitoring: https://monitoring.example.com/events
  logging: https://logs.example.com/api
  error_tracking: https://errors.example.com/report

webhooks:
  - url: https://webhook.example.com/events
    events: ['user.created', 'user.updated']
  - url: https://hooks.slack.com/services/XXX/YYY/ZZZ
    events: ['deployment.success', 'deployment.failure']

oauth:
  google:
    client_id: '123456789'
    auth_url: https://accounts.google.com/o/oauth2/v2/auth
    token_url: https://oauth2.googleapis.com/token
  github:
    client_id: 'abcdefgh'
    auth_url: https://github.com/login/oauth/authorize
    token_url: https://github.com/login/oauth/access_token

resources:
  terms_of_service: https://example.com/legal/terms
  privacy_policy: https://example.com/legal/privacy
  license: https://github.com/username/project/blob/main/LICENSE
  contributing: https://github.com/username/project/blob/main/CONTRIBUTING.md
  code_of_conduct: https://github.com/username/project/blob/main/CODE_OF_CONDUCT.md

social_media:
  twitter: https://twitter.com/example
  linkedin: https://linkedin.com/company/example
  github: https://github.com/example
  youtube: https://youtube.com/@example
  discord: https://discord.gg/example

integrations:
  stripe: https://api.stripe.com/v1
  sendgrid: https://api.sendgrid.com/v3
  twilio: https://api.twilio.com/2010-04-01
  aws_s3: https://s3.amazonaws.com/bucket-name

assets:
  logo: https://example.com/assets/logo.svg
  favicon: https://example.com/favicon.ico
  app_icon: https://example.com/assets/app-icon.png
  og_image: https://example.com/assets/og-image.jpg

development:
  local_api: http://localhost:3000/api
  staging_api: https://staging.example.com/api
  preview: https://preview-branch-123.example.com

protocols:
  secure: https://secure.example.com
  legacy: http://legacy.example.com
  websocket: wss://ws.example.com
  ftp: ftp://files.example.com
  mailto: mailto:contact@example.com
  tel: tel:+1-555-0100
